# Steal the example Docker in docker code
image: ubuntu:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind
  
variables:
  - DOCKER_HOST: "tcp://docker:2375"

before_script:
  - apt-get -q -y update
  - apt-get -q -y install docker.io
  - cat /etc/hosts
  - nslookup docker
  - docker info

# Define a vgci job that runs the tests in ./vgci/
vgci:
  script:
    - pwd
    - ls
    - ls vgci
    - ls vgci/vgci.sh
    - bash vgci/vgci.sh
