# The VG tests are going to use toil-vg.
# toil-vg needs to be able to mount paths it can see into Docker containers.
# There's no good way to do that when running Docker containers as siblings of a container containing toil-vg.
# So we either have to genuinely nest Docker inside another Docker, or we have to run the build on the real host.

before_script:
  - whoami
  - sudo apt-get -q -y update || apt-get -q -y update
  - sudo apt-get -q -y install docker.io || apt-get -q -y install docker.io
  - cat /etc/hosts
  - docker info

# Define a vgci job that runs the tests in ./vgci/
vgci:
  script:
    - pwd
    - ls
    - ls vgci
    - ls vgci/vgci.sh
    - bash vgci/vgci.sh
