# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.7 g++-4.7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
  - gcc --version && g++ --version
install: make get-deps
script: make && make test
