# Control file for continuous integration testing at http://travis-ci.org/

language: cpp
compiler: gcc
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update -qq
install: make get-deps
script: make && make test
